// Mocks generated by Mockito 5.4.4 from annotations
// in media_fast_view/test/features/favorites/presentation/view_models/slideshow_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:media_fast_view/features/media_library/domain/entities/media_entity.dart'
    as _i4;
import 'package:media_fast_view/features/tagging/domain/entities/tag_entity.dart'
    as _i5;
import 'package:media_fast_view/shared/utils/tag_mutation_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTagMutationResult_0 extends _i1.SmartFake
    implements _i2.TagMutationResult {
  _FakeTagMutationResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TagMutationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagMutationService extends _i1.Mock
    implements _i2.TagMutationService {
  MockTagMutationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.TagMutationResult> toggleTagForMedia(
    _i4.MediaEntity? media,
    _i5.TagEntity? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleTagForMedia,
          [
            media,
            tag,
          ],
        ),
        returnValue:
            _i3.Future<_i2.TagMutationResult>.value(_FakeTagMutationResult_0(
          this,
          Invocation.method(
            #toggleTagForMedia,
            [
              media,
              tag,
            ],
          ),
        )),
      ) as _i3.Future<_i2.TagMutationResult>);
}
