// Mocks generated by Mockito 5.4.4 from annotations
// in media_fast_view/test/core/services/permission_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:media_fast_view/core/services/bookmark_service.dart' as _i3;
import 'package:media_fast_view/core/services/file_transfer_result.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFileTransferResult_0 extends _i1.SmartFake
    implements _i2.FileTransferResult {
  _FakeFileTransferResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookmarkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookmarkService extends _i1.Mock implements _i3.BookmarkService {
  MockBookmarkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> createBookmark(String? directoryPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBookmark,
          [directoryPath],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #createBookmark,
            [directoryPath],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> createFileBookmark(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFileBookmark,
          [filePath],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #createFileBookmark,
            [filePath],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> selectDirectoryAndCreateBookmark(
          {String? initialDirectoryPath}) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectDirectoryAndCreateBookmark,
          [],
          {#initialDirectoryPath: initialDirectoryPath},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<String> resolveBookmark(String? bookmarkData) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveBookmark,
          [bookmarkData],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #resolveBookmark,
            [bookmarkData],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> stopAccessingBookmark(String? bookmarkData) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopAccessingBookmark,
          [bookmarkData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isBookmarkValid(String? bookmarkData) => (super.noSuchMethod(
        Invocation.method(
          #isBookmarkValid,
          [bookmarkData],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String> startAccessingBookmark(String? bookmarkData) =>
      (super.noSuchMethod(
        Invocation.method(
          #startAccessingBookmark,
          [bookmarkData],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #startAccessingBookmark,
            [bookmarkData],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String?> moveToTrash(
    String? path, {
    String? bookmarkData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveToTrash,
          [path],
          {#bookmarkData: bookmarkData},
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> revealInFinder(
    String? path, {
    String? bookmarkData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #revealInFinder,
          [path],
          {#bookmarkData: bookmarkData},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.FileTransferResult> moveItem({
    required String? sourcePath,
    required String? destinationPath,
    String? sourceBookmarkData,
    String? destinationBookmarkData,
    _i2.ConflictStrategy? conflictStrategy = _i2.ConflictStrategy.fail,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveItem,
          [],
          {
            #sourcePath: sourcePath,
            #destinationPath: destinationPath,
            #sourceBookmarkData: sourceBookmarkData,
            #destinationBookmarkData: destinationBookmarkData,
            #conflictStrategy: conflictStrategy,
          },
        ),
        returnValue:
            _i4.Future<_i2.FileTransferResult>.value(_FakeFileTransferResult_0(
          this,
          Invocation.method(
            #moveItem,
            [],
            {
              #sourcePath: sourcePath,
              #destinationPath: destinationPath,
              #sourceBookmarkData: sourceBookmarkData,
              #destinationBookmarkData: destinationBookmarkData,
              #conflictStrategy: conflictStrategy,
            },
          ),
        )),
      ) as _i4.Future<_i2.FileTransferResult>);

  @override
  _i4.Future<_i2.FileTransferResult> copyItem({
    required String? sourcePath,
    required String? destinationPath,
    String? sourceBookmarkData,
    String? destinationBookmarkData,
    _i2.ConflictStrategy? conflictStrategy = _i2.ConflictStrategy.fail,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyItem,
          [],
          {
            #sourcePath: sourcePath,
            #destinationPath: destinationPath,
            #sourceBookmarkData: sourceBookmarkData,
            #destinationBookmarkData: destinationBookmarkData,
            #conflictStrategy: conflictStrategy,
          },
        ),
        returnValue:
            _i4.Future<_i2.FileTransferResult>.value(_FakeFileTransferResult_0(
          this,
          Invocation.method(
            #copyItem,
            [],
            {
              #sourcePath: sourcePath,
              #destinationPath: destinationPath,
              #sourceBookmarkData: sourceBookmarkData,
              #destinationBookmarkData: destinationBookmarkData,
              #conflictStrategy: conflictStrategy,
            },
          ),
        )),
      ) as _i4.Future<_i2.FileTransferResult>);
}
