// Mocks generated by Mockito 5.4.4 from annotations
// in media_fast_view/test/features/full_screen/presentation/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i9;
import 'package:media_fast_view/core/utils/batch_update_result.dart' as _i5;
import 'package:media_fast_view/features/favorites/domain/entities/favorite_entity.dart'
    as _i15;
import 'package:media_fast_view/features/favorites/domain/entities/favorite_item_type.dart'
    as _i12;
import 'package:media_fast_view/features/favorites/domain/repositories/favorites_repository.dart'
    as _i14;
import 'package:media_fast_view/features/favorites/presentation/view_models/favorites_view_model.dart'
    as _i2;
import 'package:media_fast_view/features/full_screen/domain/use_cases/load_media_for_viewing_use_case.dart'
    as _i6;
import 'package:media_fast_view/features/media_library/domain/entities/directory_entity.dart'
    as _i11;
import 'package:media_fast_view/features/media_library/domain/entities/media_entity.dart'
    as _i8;
import 'package:media_fast_view/features/media_library/domain/repositories/directory_repository.dart'
    as _i3;
import 'package:media_fast_view/features/media_library/domain/repositories/media_repository.dart'
    as _i4;
import 'package:media_fast_view/features/tagging/domain/entities/tag_entity.dart'
    as _i17;
import 'package:media_fast_view/features/tagging/domain/use_cases/assign_tag_use_case.dart'
    as _i16;
import 'package:media_fast_view/shared/utils/tag_cache_refresher.dart' as _i19;
import 'package:media_fast_view/shared/utils/tag_lookup.dart' as _i18;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:state_notifier/state_notifier.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFavoritesBatchResult_0 extends _i1.SmartFake
    implements _i2.FavoritesBatchResult {
  _FakeFavoritesBatchResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDirectoryRepository_1 extends _i1.SmartFake
    implements _i3.DirectoryRepository {
  _FakeDirectoryRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMediaRepository_2 extends _i1.SmartFake
    implements _i4.MediaRepository {
  _FakeMediaRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchUpdateResult_3 extends _i1.SmartFake
    implements _i5.BatchUpdateResult {
  _FakeBatchUpdateResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoadMediaForViewingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadMediaForViewingUseCase extends _i1.Mock
    implements _i6.LoadMediaForViewingUseCase {
  MockLoadMediaForViewingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i8.MediaEntity>> call(
    String? directoryPath,
    String? directoryId, {
    String? bookmarkData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            directoryPath,
            directoryId,
          ],
          {#bookmarkData: bookmarkData},
        ),
        returnValue:
            _i7.Future<List<_i8.MediaEntity>>.value(<_i8.MediaEntity>[]),
      ) as _i7.Future<List<_i8.MediaEntity>>);
}

/// A class which mocks [FavoritesViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesViewModel extends _i1.Mock
    implements _i2.FavoritesViewModel {
  MockFavoritesViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasLoadedFavorites => (super.noSuchMethod(
        Invocation.getter(#hasLoadedFavorites),
        returnValue: false,
      ) as bool);

  @override
  set onError(_i9.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i7.Stream<_i2.FavoritesState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<_i2.FavoritesState>.empty(),
      ) as _i7.Stream<_i2.FavoritesState>);

  @override
  _i2.FavoritesState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i10.dummyValue<_i2.FavoritesState>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.FavoritesState);

  @override
  set state(_i2.FavoritesState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.FavoritesState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _i10.dummyValue<_i2.FavoritesState>(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.FavoritesState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> loadFavorites() => (super.noSuchMethod(
        Invocation.method(
          #loadFavorites,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> toggleFavorite(_i8.MediaEntity? media) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [media],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.FavoritesBatchResult> toggleFavoritesForMedia(
          List<_i8.MediaEntity>? mediaItems) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavoritesForMedia,
          [mediaItems],
        ),
        returnValue: _i7.Future<_i2.FavoritesBatchResult>.value(
            _FakeFavoritesBatchResult_0(
          this,
          Invocation.method(
            #toggleFavoritesForMedia,
            [mediaItems],
          ),
        )),
      ) as _i7.Future<_i2.FavoritesBatchResult>);

  @override
  _i7.Future<_i2.FavoritesBatchResult> toggleFavoritesForDirectories(
          List<_i11.DirectoryEntity>? directories) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavoritesForDirectories,
          [directories],
        ),
        returnValue: _i7.Future<_i2.FavoritesBatchResult>.value(
            _FakeFavoritesBatchResult_0(
          this,
          Invocation.method(
            #toggleFavoritesForDirectories,
            [directories],
          ),
        )),
      ) as _i7.Future<_i2.FavoritesBatchResult>);

  @override
  _i7.Future<bool> isFavorite(
    String? itemId, {
    _i12.FavoriteItemType? type = _i12.FavoriteItemType.media,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [itemId],
          {#type: type},
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  bool isFavoriteInState(
    String? itemId, {
    _i12.FavoriteItemType? type = _i12.FavoriteItemType.media,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavoriteInState,
          [itemId],
          {#type: type},
        ),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> clearAllFavorites() => (super.noSuchMethod(
        Invocation.method(
          #clearAllFavorites,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool updateShouldNotify(
    _i2.FavoritesState? old,
    _i2.FavoritesState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i9.RemoveListener addListener(
    _i13.Listener<_i2.FavoritesState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i9.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FavoritesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesRepository extends _i1.Mock
    implements _i14.FavoritesRepository {
  MockFavoritesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i15.FavoriteEntity>> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: _i7.Future<List<_i15.FavoriteEntity>>.value(
            <_i15.FavoriteEntity>[]),
      ) as _i7.Future<List<_i15.FavoriteEntity>>);

  @override
  _i7.Future<List<String>> getFavoriteMediaIds() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteMediaIds,
          [],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<List<String>> getFavoriteDirectoryIds() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteDirectoryIds,
          [],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<void> addFavorite(String? mediaId) => (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [mediaId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addFavorites(List<_i15.FavoriteEntity>? favorites) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorites,
          [favorites],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeFavorite(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [itemId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeFavorites(List<String>? itemIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavorites,
          [itemIds],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isFavorite(
    String? itemId, {
    _i12.FavoriteItemType? type = _i12.FavoriteItemType.media,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [itemId],
          {#type: type},
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}

/// A class which mocks [AssignTagUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssignTagUseCase extends _i1.Mock implements _i16.AssignTagUseCase {
  MockAssignTagUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DirectoryRepository get directoryRepository => (super.noSuchMethod(
        Invocation.getter(#directoryRepository),
        returnValue: _FakeDirectoryRepository_1(
          this,
          Invocation.getter(#directoryRepository),
        ),
      ) as _i3.DirectoryRepository);

  @override
  _i4.MediaRepository get mediaRepository => (super.noSuchMethod(
        Invocation.getter(#mediaRepository),
        returnValue: _FakeMediaRepository_2(
          this,
          Invocation.getter(#mediaRepository),
        ),
      ) as _i4.MediaRepository);

  @override
  _i7.Future<void> setTagsForDirectory(
    String? directoryId,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTagsForDirectory,
          [
            directoryId,
            tagIds,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.BatchUpdateResult> setTagsForDirectories(
    List<String>? directoryIds,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTagsForDirectories,
          [
            directoryIds,
            tagIds,
          ],
        ),
        returnValue:
            _i7.Future<_i5.BatchUpdateResult>.value(_FakeBatchUpdateResult_3(
          this,
          Invocation.method(
            #setTagsForDirectories,
            [
              directoryIds,
              tagIds,
            ],
          ),
        )),
      ) as _i7.Future<_i5.BatchUpdateResult>);

  @override
  _i7.Future<void> assignTagToDirectory(
    String? directoryId,
    _i17.TagEntity? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignTagToDirectory,
          [
            directoryId,
            tag,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeTagFromDirectory(
    String? directoryId,
    _i17.TagEntity? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTagFromDirectory,
          [
            directoryId,
            tag,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> assignTagToMedia(
    String? mediaId,
    _i17.TagEntity? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignTagToMedia,
          [
            mediaId,
            tag,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeTagFromMedia(
    String? mediaId,
    _i17.TagEntity? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTagFromMedia,
          [
            mediaId,
            tag,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.BatchUpdateResult> setTagsForMedia(
    List<String>? mediaIds,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTagsForMedia,
          [
            mediaIds,
            tagIds,
          ],
        ),
        returnValue:
            _i7.Future<_i5.BatchUpdateResult>.value(_FakeBatchUpdateResult_3(
          this,
          Invocation.method(
            #setTagsForMedia,
            [
              mediaIds,
              tagIds,
            ],
          ),
        )),
      ) as _i7.Future<_i5.BatchUpdateResult>);

  @override
  _i7.Future<void> toggleTagOnDirectory(
    String? directoryId,
    _i17.TagEntity? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleTagOnDirectory,
          [
            directoryId,
            tag,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> toggleTagOnMedia(
    String? mediaId,
    _i17.TagEntity? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleTagOnMedia,
          [
            mediaId,
            tag,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [TagLookup].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagLookup extends _i1.Mock implements _i18.TagLookup {
  MockTagLookup() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i17.TagEntity>> getTagsByIds(Iterable<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTagsByIds,
          [ids],
        ),
        returnValue: _i7.Future<List<_i17.TagEntity>>.value(<_i17.TagEntity>[]),
      ) as _i7.Future<List<_i17.TagEntity>>);

  @override
  _i7.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i17.TagEntity>> getAllTags() => (super.noSuchMethod(
        Invocation.method(
          #getAllTags,
          [],
        ),
        returnValue: _i7.Future<List<_i17.TagEntity>>.value(<_i17.TagEntity>[]),
      ) as _i7.Future<List<_i17.TagEntity>>);
}

/// A class which mocks [TagCacheRefresher].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagCacheRefresher extends _i1.Mock implements _i19.TagCacheRefresher {
  MockTagCacheRefresher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
