// Mocks generated by Mockito 5.4.4 from annotations
// in media_fast_view/test/features/tagging/domain/use_cases/create_tag_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:media_fast_view/features/media_library/domain/entities/tag_entity.dart'
    as _i4;
import 'package:media_fast_view/features/media_library/domain/repositories/tag_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TagRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagRepository extends _i1.Mock implements _i2.TagRepository {
  MockTagRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TagEntity>> getTags() => (super.noSuchMethod(
        Invocation.method(
          #getTags,
          [],
        ),
        returnValue: _i3.Future<List<_i4.TagEntity>>.value(<_i4.TagEntity>[]),
      ) as _i3.Future<List<_i4.TagEntity>>);

  @override
  _i3.Future<_i4.TagEntity?> getTagById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTagById,
          [id],
        ),
        returnValue: _i3.Future<_i4.TagEntity?>.value(),
      ) as _i3.Future<_i4.TagEntity?>);

  @override
  _i3.Future<void> createTag(_i4.TagEntity? tag) => (super.noSuchMethod(
        Invocation.method(
          #createTag,
          [tag],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateTag(_i4.TagEntity? tag) => (super.noSuchMethod(
        Invocation.method(
          #updateTag,
          [tag],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTag(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTag,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearTags() => (super.noSuchMethod(
        Invocation.method(
          #clearTags,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
