// Mocks generated by Mockito 5.4.4 from annotations
// in media_fast_view/test/features/full_screen/domain/use_cases/load_media_for_viewing_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:media_fast_view/core/utils/batch_update_result.dart' as _i2;
import 'package:media_fast_view/features/media_library/data/isar/isar_media_data_source.dart'
    as _i3;
import 'package:media_fast_view/features/media_library/data/models/media_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBatchUpdateResult_0 extends _i1.SmartFake
    implements _i2.BatchUpdateResult {
  _FakeBatchUpdateResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IsarMediaDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsarMediaDataSource extends _i1.Mock
    implements _i3.IsarMediaDataSource {
  MockIsarMediaDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get profileId => (super.noSuchMethod(
        Invocation.getter(#profileId),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#profileId),
        ),
      ) as String);

  @override
  _i5.Future<List<_i6.MediaModel>> getMedia() => (super.noSuchMethod(
        Invocation.method(
          #getMedia,
          [],
        ),
        returnValue: _i5.Future<List<_i6.MediaModel>>.value(<_i6.MediaModel>[]),
      ) as _i5.Future<List<_i6.MediaModel>>);

  @override
  _i5.Future<void> saveMedia(List<_i6.MediaModel>? media) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMedia,
          [media],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> upsertMedia(List<_i6.MediaModel>? media) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertMedia,
          [media],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.MediaModel>> getMediaForDirectory(String? directoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaForDirectory,
          [directoryId],
        ),
        returnValue: _i5.Future<List<_i6.MediaModel>>.value(<_i6.MediaModel>[]),
      ) as _i5.Future<List<_i6.MediaModel>>);

  @override
  _i5.Future<void> addMedia(List<_i6.MediaModel>? mediaItems) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMedia,
          [mediaItems],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateMediaTags(
    String? mediaId,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMediaTags,
          [
            mediaId,
            tagIds,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.BatchUpdateResult> updateMediaTagsBatch(
          Map<String, List<String>>? mediaTags) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMediaTagsBatch,
          [mediaTags],
        ),
        returnValue:
            _i5.Future<_i2.BatchUpdateResult>.value(_FakeBatchUpdateResult_0(
          this,
          Invocation.method(
            #updateMediaTagsBatch,
            [mediaTags],
          ),
        )),
      ) as _i5.Future<_i2.BatchUpdateResult>);

  @override
  _i5.Future<void> removeMediaByIds(List<String>? mediaIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMediaByIds,
          [mediaIds],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeMediaForDirectory(String? directoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMediaForDirectory,
          [directoryId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> migrateDirectoryId(
    String? legacyDirectoryId,
    String? stableDirectoryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #migrateDirectoryId,
          [
            legacyDirectoryId,
            stableDirectoryId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> relocateMedia({
    required String? mediaId,
    required String? newPath,
    required String? newName,
    required String? newDirectoryId,
    int? newSize,
    DateTime? newLastModified,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #relocateMedia,
          [],
          {
            #mediaId: mediaId,
            #newPath: newPath,
            #newName: newName,
            #newDirectoryId: newDirectoryId,
            #newSize: newSize,
            #newLastModified: newLastModified,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> replaceMedia({
    required String? oldMediaId,
    required _i6.MediaModel? newMedia,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceMedia,
          [],
          {
            #oldMediaId: oldMediaId,
            #newMedia: newMedia,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> replaceMediaBatch(
          List<({_i6.MediaModel newMedia, String oldMediaId})>? entries) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceMediaBatch,
          [entries],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.MediaModel>> getMediaUnderPath(String? directoryPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaUnderPath,
          [directoryPath],
        ),
        returnValue: _i5.Future<List<_i6.MediaModel>>.value(<_i6.MediaModel>[]),
      ) as _i5.Future<List<_i6.MediaModel>>);

  @override
  _i5.Future<void> clearMedia() => (super.noSuchMethod(
        Invocation.method(
          #clearMedia,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeMediaNotInDirectories(List<String>? directoryIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMediaNotInDirectories,
          [directoryIds],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
