// Mocks generated by Mockito 5.4.4 from annotations
// in media_fast_view/test/features/full_screen/domain/use_cases/load_media_for_viewing_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:media_fast_view/core/utils/batch_update_result.dart' as _i2;
import 'package:media_fast_view/features/media_library/data/isar/isar_media_data_source.dart'
    as _i3;
import 'package:media_fast_view/features/media_library/data/models/media_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBatchUpdateResult_0 extends _i1.SmartFake
    implements _i2.BatchUpdateResult {
  _FakeBatchUpdateResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IsarMediaDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsarMediaDataSource extends _i1.Mock
    implements _i3.IsarMediaDataSource {
  MockIsarMediaDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.MediaModel>> getMedia() => (super.noSuchMethod(
        Invocation.method(
          #getMedia,
          [],
        ),
        returnValue: _i4.Future<List<_i5.MediaModel>>.value(<_i5.MediaModel>[]),
      ) as _i4.Future<List<_i5.MediaModel>>);

  @override
  _i4.Future<void> saveMedia(List<_i5.MediaModel>? media) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMedia,
          [media],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> upsertMedia(List<_i5.MediaModel>? media) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertMedia,
          [media],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.MediaModel>> getMediaForDirectory(String? directoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaForDirectory,
          [directoryId],
        ),
        returnValue: _i4.Future<List<_i5.MediaModel>>.value(<_i5.MediaModel>[]),
      ) as _i4.Future<List<_i5.MediaModel>>);

  @override
  _i4.Future<void> addMedia(List<_i5.MediaModel>? mediaItems) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMedia,
          [mediaItems],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateMediaTags(
    String? mediaId,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMediaTags,
          [
            mediaId,
            tagIds,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.BatchUpdateResult> updateMediaTagsBatch(
          Map<String, List<String>>? mediaTags) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMediaTagsBatch,
          [mediaTags],
        ),
        returnValue:
            _i4.Future<_i2.BatchUpdateResult>.value(_FakeBatchUpdateResult_0(
          this,
          Invocation.method(
            #updateMediaTagsBatch,
            [mediaTags],
          ),
        )),
      ) as _i4.Future<_i2.BatchUpdateResult>);

  @override
  _i4.Future<void> removeMediaForDirectory(String? directoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMediaForDirectory,
          [directoryId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> migrateDirectoryId(
    String? legacyDirectoryId,
    String? stableDirectoryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #migrateDirectoryId,
          [
            legacyDirectoryId,
            stableDirectoryId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearMedia() => (super.noSuchMethod(
        Invocation.method(
          #clearMedia,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeMediaNotInDirectories(List<String>? directoryIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMediaNotInDirectories,
          [directoryIds],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
