// Mocks generated by Mockito 5.4.4 from annotations
// in media_fast_view/test/features/media_library/data/repositories/directory_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:media_fast_view/core/services/bookmark_service.dart' as _i2;
import 'package:media_fast_view/core/services/file_transfer_result.dart' as _i6;
import 'package:media_fast_view/core/services/permission_service.dart' as _i7;
import 'package:media_fast_view/core/utils/batch_update_result.dart' as _i5;
import 'package:media_fast_view/features/media_library/data/data_sources/filesystem_media_data_source.dart'
    as _i4;
import 'package:media_fast_view/features/media_library/data/data_sources/local_directory_data_source.dart'
    as _i3;
import 'package:media_fast_view/features/media_library/data/isar/isar_directory_data_source.dart'
    as _i12;
import 'package:media_fast_view/features/media_library/data/isar/isar_media_data_source.dart'
    as _i11;
import 'package:media_fast_view/features/media_library/data/models/directory_model.dart'
    as _i14;
import 'package:media_fast_view/features/media_library/data/models/media_model.dart'
    as _i10;
import 'package:media_fast_view/features/media_library/domain/entities/directory_entity.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBookmarkService_0 extends _i1.SmartFake
    implements _i2.BookmarkService {
  _FakeBookmarkService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDirectoryTreeFingerprint_1 extends _i1.SmartFake
    implements _i3.DirectoryTreeFingerprint {
  _FakeDirectoryTreeFingerprint_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePermissionValidationResult_2 extends _i1.SmartFake
    implements _i4.PermissionValidationResult {
  _FakePermissionValidationResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchUpdateResult_3 extends _i1.SmartFake
    implements _i5.BatchUpdateResult {
  _FakeBatchUpdateResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileTransferResult_4 extends _i1.SmartFake
    implements _i6.FileTransferResult {
  _FakeFileTransferResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBookmarkValidationResult_5 extends _i1.SmartFake
    implements _i7.BookmarkValidationResult {
  _FakeBookmarkValidationResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePermissionMonitorResult_6 extends _i1.SmartFake
    implements _i7.PermissionMonitorResult {
  _FakePermissionMonitorResult_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalDirectoryDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDirectoryDataSource extends _i1.Mock
    implements _i3.LocalDirectoryDataSource {
  MockLocalDirectoryDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BookmarkService get bookmarkService => (super.noSuchMethod(
        Invocation.getter(#bookmarkService),
        returnValue: _FakeBookmarkService_0(
          this,
          Invocation.getter(#bookmarkService),
        ),
      ) as _i2.BookmarkService);

  @override
  _i8.Future<bool> validateDirectory(_i9.DirectoryEntity? directory) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateDirectory,
          [directory],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i9.DirectoryEntity?> getDirectoryInfo(String? directoryPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDirectoryInfo,
          [directoryPath],
        ),
        returnValue: _i8.Future<_i9.DirectoryEntity?>.value(),
      ) as _i8.Future<_i9.DirectoryEntity?>);

  @override
  _i8.Future<List<_i9.DirectoryEntity>> scanDirectoriesWithMedia(
    _i9.DirectoryEntity? rootDirectory, {
    _i3.DirectoryScanProgressCallback? onProgress,
    _i3.DirectoryScanCancellationToken? cancellationToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanDirectoriesWithMedia,
          [rootDirectory],
          {
            #onProgress: onProgress,
            #cancellationToken: cancellationToken,
          },
        ),
        returnValue: _i8.Future<List<_i9.DirectoryEntity>>.value(
            <_i9.DirectoryEntity>[]),
      ) as _i8.Future<List<_i9.DirectoryEntity>>);

  @override
  _i8.Future<_i3.DirectoryTreeFingerprint> fingerprintDirectoryTree(
          _i9.DirectoryEntity? rootDirectory) =>
      (super.noSuchMethod(
        Invocation.method(
          #fingerprintDirectoryTree,
          [rootDirectory],
        ),
        returnValue: _i8.Future<_i3.DirectoryTreeFingerprint>.value(
            _FakeDirectoryTreeFingerprint_1(
          this,
          Invocation.method(
            #fingerprintDirectoryTree,
            [rootDirectory],
          ),
        )),
      ) as _i8.Future<_i3.DirectoryTreeFingerprint>);

  @override
  _i8.Future<List<String>> scanSubdirectories(String? directoryPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanSubdirectories,
          [directoryPath],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);
}

/// A class which mocks [FilesystemMediaDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilesystemMediaDataSource extends _i1.Mock
    implements _i4.FilesystemMediaDataSource {
  MockFilesystemMediaDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.PermissionValidationResult> validateDirectoryAccess(
    String? directoryPath, {
    String? bookmarkData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateDirectoryAccess,
          [directoryPath],
          {#bookmarkData: bookmarkData},
        ),
        returnValue: _i8.Future<_i4.PermissionValidationResult>.value(
            _FakePermissionValidationResult_2(
          this,
          Invocation.method(
            #validateDirectoryAccess,
            [directoryPath],
            {#bookmarkData: bookmarkData},
          ),
        )),
      ) as _i8.Future<_i4.PermissionValidationResult>);

  @override
  _i8.Future<List<_i10.MediaModel>> scanMediaForDirectory(
    String? directoryPath,
    String? directoryId, {
    String? bookmarkData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanMediaForDirectory,
          [
            directoryPath,
            directoryId,
          ],
          {#bookmarkData: bookmarkData},
        ),
        returnValue:
            _i8.Future<List<_i10.MediaModel>>.value(<_i10.MediaModel>[]),
      ) as _i8.Future<List<_i10.MediaModel>>);

  @override
  _i8.Future<List<String>> scanSubdirectories(String? directoryPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanSubdirectories,
          [directoryPath],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<_i10.MediaModel?> getMediaById(
    String? mediaId,
    String? directoryPath,
    String? directoryId, {
    String? bookmarkData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaById,
          [
            mediaId,
            directoryPath,
            directoryId,
          ],
          {#bookmarkData: bookmarkData},
        ),
        returnValue: _i8.Future<_i10.MediaModel?>.value(),
      ) as _i8.Future<_i10.MediaModel?>);

  @override
  _i8.Future<List<_i10.MediaModel>> filterMediaByTags(
    String? directoryPath,
    String? directoryId,
    List<String>? tagIds, {
    String? bookmarkData,
    _i11.IsarMediaDataSource? mediaPersistence,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterMediaByTags,
          [
            directoryPath,
            directoryId,
            tagIds,
          ],
          {
            #bookmarkData: bookmarkData,
            #mediaPersistence: mediaPersistence,
          },
        ),
        returnValue:
            _i8.Future<List<_i10.MediaModel>>.value(<_i10.MediaModel>[]),
      ) as _i8.Future<List<_i10.MediaModel>>);
}

/// A class which mocks [IsarDirectoryDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsarDirectoryDataSource extends _i1.Mock
    implements _i12.IsarDirectoryDataSource {
  MockIsarDirectoryDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get profileId => (super.noSuchMethod(
        Invocation.getter(#profileId),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#profileId),
        ),
      ) as String);

  @override
  _i8.Future<List<_i14.DirectoryModel>> getDirectories() => (super.noSuchMethod(
        Invocation.method(
          #getDirectories,
          [],
        ),
        returnValue: _i8.Future<List<_i14.DirectoryModel>>.value(
            <_i14.DirectoryModel>[]),
      ) as _i8.Future<List<_i14.DirectoryModel>>);

  @override
  _i8.Future<_i14.DirectoryModel?> getDirectoryById(String? directoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDirectoryById,
          [directoryId],
        ),
        returnValue: _i8.Future<_i14.DirectoryModel?>.value(),
      ) as _i8.Future<_i14.DirectoryModel?>);

  @override
  _i8.Future<_i14.DirectoryModel?> getDirectoryByPathUnscoped(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDirectoryByPathUnscoped,
          [path],
        ),
        returnValue: _i8.Future<_i14.DirectoryModel?>.value(),
      ) as _i8.Future<_i14.DirectoryModel?>);

  @override
  _i8.Future<void> saveDirectories(List<_i14.DirectoryModel>? directories) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDirectories,
          [directories],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addDirectory(_i14.DirectoryModel? directory) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDirectory,
          [directory],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeDirectory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #removeDirectory,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateDirectory(_i14.DirectoryModel? updatedDirectory) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDirectory,
          [updatedDirectory],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i5.BatchUpdateResult> updateDirectoryTagsBatch(
          Map<String, List<String>>? directoryTags) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDirectoryTagsBatch,
          [directoryTags],
        ),
        returnValue:
            _i8.Future<_i5.BatchUpdateResult>.value(_FakeBatchUpdateResult_3(
          this,
          Invocation.method(
            #updateDirectoryTagsBatch,
            [directoryTags],
          ),
        )),
      ) as _i8.Future<_i5.BatchUpdateResult>);

  @override
  _i8.Future<void> clearDirectories() => (super.noSuchMethod(
        Invocation.method(
          #clearDirectories,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [IsarMediaDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsarMediaDataSource extends _i1.Mock
    implements _i11.IsarMediaDataSource {
  MockIsarMediaDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get profileId => (super.noSuchMethod(
        Invocation.getter(#profileId),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#profileId),
        ),
      ) as String);

  @override
  _i8.Future<List<_i10.MediaModel>> getMedia() => (super.noSuchMethod(
        Invocation.method(
          #getMedia,
          [],
        ),
        returnValue:
            _i8.Future<List<_i10.MediaModel>>.value(<_i10.MediaModel>[]),
      ) as _i8.Future<List<_i10.MediaModel>>);

  @override
  _i8.Future<void> saveMedia(List<_i10.MediaModel>? media) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMedia,
          [media],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> upsertMedia(List<_i10.MediaModel>? media) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertMedia,
          [media],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i10.MediaModel>> getMediaForDirectory(String? directoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaForDirectory,
          [directoryId],
        ),
        returnValue:
            _i8.Future<List<_i10.MediaModel>>.value(<_i10.MediaModel>[]),
      ) as _i8.Future<List<_i10.MediaModel>>);

  @override
  _i8.Future<void> addMedia(List<_i10.MediaModel>? mediaItems) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMedia,
          [mediaItems],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateMediaTags(
    String? mediaId,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMediaTags,
          [
            mediaId,
            tagIds,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i5.BatchUpdateResult> updateMediaTagsBatch(
          Map<String, List<String>>? mediaTags) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMediaTagsBatch,
          [mediaTags],
        ),
        returnValue:
            _i8.Future<_i5.BatchUpdateResult>.value(_FakeBatchUpdateResult_3(
          this,
          Invocation.method(
            #updateMediaTagsBatch,
            [mediaTags],
          ),
        )),
      ) as _i8.Future<_i5.BatchUpdateResult>);

  @override
  _i8.Future<void> removeMediaByIds(List<String>? mediaIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMediaByIds,
          [mediaIds],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeMediaForDirectory(String? directoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMediaForDirectory,
          [directoryId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> migrateDirectoryId(
    String? legacyDirectoryId,
    String? stableDirectoryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #migrateDirectoryId,
          [
            legacyDirectoryId,
            stableDirectoryId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> relocateMedia({
    required String? mediaId,
    required String? newPath,
    required String? newName,
    required String? newDirectoryId,
    int? newSize,
    DateTime? newLastModified,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #relocateMedia,
          [],
          {
            #mediaId: mediaId,
            #newPath: newPath,
            #newName: newName,
            #newDirectoryId: newDirectoryId,
            #newSize: newSize,
            #newLastModified: newLastModified,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> replaceMedia({
    required String? oldMediaId,
    required _i10.MediaModel? newMedia,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceMedia,
          [],
          {
            #oldMediaId: oldMediaId,
            #newMedia: newMedia,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> replaceMediaBatch(
          List<({_i10.MediaModel newMedia, String oldMediaId})>? entries) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceMediaBatch,
          [entries],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i10.MediaModel>> getMediaUnderPath(String? directoryPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaUnderPath,
          [directoryPath],
        ),
        returnValue:
            _i8.Future<List<_i10.MediaModel>>.value(<_i10.MediaModel>[]),
      ) as _i8.Future<List<_i10.MediaModel>>);

  @override
  _i8.Future<void> clearMedia() => (super.noSuchMethod(
        Invocation.method(
          #clearMedia,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeMediaNotInDirectories(List<String>? directoryIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMediaNotInDirectories,
          [directoryIds],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [BookmarkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookmarkService extends _i1.Mock implements _i2.BookmarkService {
  MockBookmarkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> createBookmark(String? directoryPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBookmark,
          [directoryPath],
        ),
        returnValue: _i8.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #createBookmark,
            [directoryPath],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<Map<String, dynamic>> selectDirectoryAndCreateBookmark(
          {String? initialDirectoryPath}) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectDirectoryAndCreateBookmark,
          [],
          {#initialDirectoryPath: initialDirectoryPath},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<String> resolveBookmark(String? bookmarkData) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveBookmark,
          [bookmarkData],
        ),
        returnValue: _i8.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #resolveBookmark,
            [bookmarkData],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<void> stopAccessingBookmark(String? bookmarkData) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopAccessingBookmark,
          [bookmarkData],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> isBookmarkValid(String? bookmarkData) => (super.noSuchMethod(
        Invocation.method(
          #isBookmarkValid,
          [bookmarkData],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<String> startAccessingBookmark(String? bookmarkData) =>
      (super.noSuchMethod(
        Invocation.method(
          #startAccessingBookmark,
          [bookmarkData],
        ),
        returnValue: _i8.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #startAccessingBookmark,
            [bookmarkData],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<String?> moveToTrash(
    String? path, {
    String? bookmarkData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveToTrash,
          [path],
          {#bookmarkData: bookmarkData},
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<void> revealInFinder(
    String? path, {
    String? bookmarkData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #revealInFinder,
          [path],
          {#bookmarkData: bookmarkData},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i6.FileTransferResult> moveItem({
    required String? sourcePath,
    required String? destinationPath,
    String? sourceBookmarkData,
    String? destinationBookmarkData,
    _i6.ConflictStrategy? conflictStrategy = _i6.ConflictStrategy.fail,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveItem,
          [],
          {
            #sourcePath: sourcePath,
            #destinationPath: destinationPath,
            #sourceBookmarkData: sourceBookmarkData,
            #destinationBookmarkData: destinationBookmarkData,
            #conflictStrategy: conflictStrategy,
          },
        ),
        returnValue:
            _i8.Future<_i6.FileTransferResult>.value(_FakeFileTransferResult_4(
          this,
          Invocation.method(
            #moveItem,
            [],
            {
              #sourcePath: sourcePath,
              #destinationPath: destinationPath,
              #sourceBookmarkData: sourceBookmarkData,
              #destinationBookmarkData: destinationBookmarkData,
              #conflictStrategy: conflictStrategy,
            },
          ),
        )),
      ) as _i8.Future<_i6.FileTransferResult>);

  @override
  _i8.Future<_i6.FileTransferResult> copyItem({
    required String? sourcePath,
    required String? destinationPath,
    String? sourceBookmarkData,
    String? destinationBookmarkData,
    _i6.ConflictStrategy? conflictStrategy = _i6.ConflictStrategy.fail,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyItem,
          [],
          {
            #sourcePath: sourcePath,
            #destinationPath: destinationPath,
            #sourceBookmarkData: sourceBookmarkData,
            #destinationBookmarkData: destinationBookmarkData,
            #conflictStrategy: conflictStrategy,
          },
        ),
        returnValue:
            _i8.Future<_i6.FileTransferResult>.value(_FakeFileTransferResult_4(
          this,
          Invocation.method(
            #copyItem,
            [],
            {
              #sourcePath: sourcePath,
              #destinationPath: destinationPath,
              #sourceBookmarkData: sourceBookmarkData,
              #destinationBookmarkData: destinationBookmarkData,
              #conflictStrategy: conflictStrategy,
            },
          ),
        )),
      ) as _i8.Future<_i6.FileTransferResult>);
}

/// A class which mocks [PermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionService extends _i1.Mock implements _i7.PermissionService {
  MockPermissionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<bool> hasStoragePermission() => (super.noSuchMethod(
        Invocation.method(
          #hasStoragePermission,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> requestStoragePermission() => (super.noSuchMethod(
        Invocation.method(
          #requestStoragePermission,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i7.PermissionStatus> checkDirectoryAccess(
          String? directoryPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkDirectoryAccess,
          [directoryPath],
        ),
        returnValue: _i8.Future<_i7.PermissionStatus>.value(
            _i7.PermissionStatus.granted),
      ) as _i8.Future<_i7.PermissionStatus>);

  @override
  _i8.Future<_i7.BookmarkValidationResult> validateBookmark(
          String? bookmarkData) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateBookmark,
          [bookmarkData],
        ),
        returnValue: _i8.Future<_i7.BookmarkValidationResult>.value(
            _FakeBookmarkValidationResult_5(
          this,
          Invocation.method(
            #validateBookmark,
            [bookmarkData],
          ),
        )),
      ) as _i8.Future<_i7.BookmarkValidationResult>);

  @override
  _i8.Future<_i7.DirectoryRecoveryResult?> recoverDirectoryAccess(
          String? directoryPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverDirectoryAccess,
          [directoryPath],
        ),
        returnValue: _i8.Future<_i7.DirectoryRecoveryResult?>.value(),
      ) as _i8.Future<_i7.DirectoryRecoveryResult?>);

  @override
  _i8.Future<String?> renewBookmark(
    String? expiredBookmarkData,
    String? directoryPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renewBookmark,
          [
            expiredBookmarkData,
            directoryPath,
          ],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<_i7.BookmarkValidationResult> validateAndRenewBookmark(
    String? bookmarkData,
    String? directoryPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateAndRenewBookmark,
          [
            bookmarkData,
            directoryPath,
          ],
        ),
        returnValue: _i8.Future<_i7.BookmarkValidationResult>.value(
            _FakeBookmarkValidationResult_5(
          this,
          Invocation.method(
            #validateAndRenewBookmark,
            [
              bookmarkData,
              directoryPath,
            ],
          ),
        )),
      ) as _i8.Future<_i7.BookmarkValidationResult>);

  @override
  void logPermissionEvent(
    String? event, {
    String? path,
    String? error,
    String? details,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logPermissionEvent,
          [event],
          {
            #path: path,
            #error: error,
            #details: details,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<bool> canAccessPath(String? path) => (super.noSuchMethod(
        Invocation.method(
          #canAccessPath,
          [path],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> canWriteToPath(String? path) => (super.noSuchMethod(
        Invocation.method(
          #canWriteToPath,
          [path],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> ensureStoragePermission() => (super.noSuchMethod(
        Invocation.method(
          #ensureStoragePermission,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> ensurePathAccessible(String? path) => (super.noSuchMethod(
        Invocation.method(
          #ensurePathAccessible,
          [path],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> ensurePathWritable(String? path) => (super.noSuchMethod(
        Invocation.method(
          #ensurePathWritable,
          [path],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i7.PermissionMonitorResult> monitorDirectoryPermissions(
    String? directoryPath, {
    String? bookmarkData,
    Duration? checkInterval = const Duration(minutes: 5),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #monitorDirectoryPermissions,
          [directoryPath],
          {
            #bookmarkData: bookmarkData,
            #checkInterval: checkInterval,
          },
        ),
        returnValue: _i8.Future<_i7.PermissionMonitorResult>.value(
            _FakePermissionMonitorResult_6(
          this,
          Invocation.method(
            #monitorDirectoryPermissions,
            [directoryPath],
            {
              #bookmarkData: bookmarkData,
              #checkInterval: checkInterval,
            },
          ),
        )),
      ) as _i8.Future<_i7.PermissionMonitorResult>);

  @override
  _i8.Future<List<_i7.DirectoryPermissionStatus>> validateMultipleDirectories(
    List<String>? directoryPaths, {
    Map<String, String?>? bookmarkDataMap,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateMultipleDirectories,
          [directoryPaths],
          {#bookmarkDataMap: bookmarkDataMap},
        ),
        returnValue: _i8.Future<List<_i7.DirectoryPermissionStatus>>.value(
            <_i7.DirectoryPermissionStatus>[]),
      ) as _i8.Future<List<_i7.DirectoryPermissionStatus>>);
}
