// Mocks generated by Mockito 5.4.4 from annotations
// in media_fast_view/test/features/media_library/data/repositories/tag_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:media_fast_view/features/media_library/data/models/tag_model.dart'
    as _i4;
import 'package:media_fast_view/features/tagging/data/isar/isar_tag_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IsarTagDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsarTagDataSource extends _i1.Mock implements _i2.IsarTagDataSource {
  MockIsarTagDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TagModel>> getTags() => (super.noSuchMethod(
        Invocation.method(
          #getTags,
          [],
        ),
        returnValue: _i3.Future<List<_i4.TagModel>>.value(<_i4.TagModel>[]),
      ) as _i3.Future<List<_i4.TagModel>>);

  @override
  _i3.Future<void> saveTags(List<_i4.TagModel>? tags) => (super.noSuchMethod(
        Invocation.method(
          #saveTags,
          [tags],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addTag(_i4.TagModel? tag) => (super.noSuchMethod(
        Invocation.method(
          #addTag,
          [tag],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateTag(_i4.TagModel? tag) => (super.noSuchMethod(
        Invocation.method(
          #updateTag,
          [tag],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeTag(String? id) => (super.noSuchMethod(
        Invocation.method(
          #removeTag,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearTags() => (super.noSuchMethod(
        Invocation.method(
          #clearTags,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.TagModel>> getTagsForMedia(String? mediaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTagsForMedia,
          [mediaId],
        ),
        returnValue: _i3.Future<List<_i4.TagModel>>.value(<_i4.TagModel>[]),
      ) as _i3.Future<List<_i4.TagModel>>);

  @override
  _i3.Future<List<_i4.TagModel>> getTagsForDirectory(String? directoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTagsForDirectory,
          [directoryId],
        ),
        returnValue: _i3.Future<List<_i4.TagModel>>.value(<_i4.TagModel>[]),
      ) as _i3.Future<List<_i4.TagModel>>);
}
