import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:media_fast_view/features/media_library/domain/entities/media_entity.dart';
import 'package:media_fast_view/features/thumbnails/domain/thumbnail_request.dart';
import 'package:media_fast_view/features/thumbnails/domain/thumbnail_result.dart';
import 'package:media_fast_view/features/thumbnails/presentation/media_thumbnail.dart';
import 'package:media_fast_view/features/thumbnails/presentation/thumbnail_providers.dart';
import 'package:media_fast_view/shared/providers/settings_providers.dart';

final Uint8List _transparentPng = base64Decode(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk'
  '+A8AAQUBAScY42YAAAAASUVORK5CYII=',
);

MediaEntity _video() {
  return MediaEntity(
    id: 'video-1',
    path: '/Library/example.mov',
    name: 'example.mov',
    type: MediaType.video,
    size: 42,
    lastModified: DateTime(2025),
    tagIds: const <String>[],
    directoryId: 'library',
    bookmarkData: 'bookmark',
  );
}

Widget _subject() {
  return MaterialApp(
    home: Scaffold(
      body: SizedBox(
        width: 120,
        height: 80,
        child: MediaThumbnail(
          media: _video(),
          placeholderBuilder: (_) => const ColoredBox(
            key: Key('thumbnail-loading'),
            color: Colors.grey,
          ),
          errorBuilder: (_) =>
              const ColoredBox(key: Key('thumbnail-error'), color: Colors.red),
        ),
      ),
    ),
  );
}

void main() {
  testWidgets('shows a placeholder before rendering generated bytes', (
    tester,
  ) async {
    final result = Completer<ThumbnailResult>();
    ThumbnailRequest? capturedRequest;

    await tester.pumpWidget(
      ProviderScope(
        overrides: <Override>[
          thumbnailDiskCacheEnabledProvider.overrideWithValue(false),
          thumbnailProvider.overrideWith((ref, request) {
            capturedRequest = request;
            return result.future;
          }),
        ],
        child: _subject(),
      ),
    );

    expect(find.byKey(const Key('thumbnail-loading')), findsOneWidget);
    expect(capturedRequest?.mediaType, MediaType.video);
    expect(capturedRequest?.diskCacheEnabled, isFalse);
    expect(capturedRequest?.thumbnailSize, ThumbnailSize.medium);

    result.complete(
      ThumbnailResult(
        payload: MemoryThumbnailPayload(_transparentPng),
        isCacheHit: false,
      ),
    );
    await tester.pump();

    expect(find.byType(Image), findsOneWidget);
    expect(find.byKey(const Key('thumbnail-loading')), findsNothing);
  });

  testWidgets('uses the error fallback when generation fails', (tester) async {
    await tester.pumpWidget(
      ProviderScope(
        overrides: <Override>[
          thumbnailProvider.overrideWith((ref, request) {
            throw StateError('decode failed');
          }),
        ],
        child: _subject(),
      ),
    );
    await tester.pump();

    expect(find.byKey(const Key('thumbnail-error')), findsOneWidget);
  });
}
