// Mocks generated by Mockito 5.4.4 from annotations
// in media_fast_view/test/features/favorites/domain/use_cases/toggle_favorite_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:media_fast_view/features/favorites/domain/entities/favorite_entity.dart'
    as _i4;
import 'package:media_fast_view/features/favorites/domain/entities/favorite_item_type.dart'
    as _i5;
import 'package:media_fast_view/features/favorites/domain/repositories/favorites_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FavoritesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesRepository extends _i1.Mock
    implements _i2.FavoritesRepository {
  MockFavoritesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.FavoriteEntity>> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.FavoriteEntity>>.value(<_i4.FavoriteEntity>[]),
      ) as _i3.Future<List<_i4.FavoriteEntity>>);

  @override
  _i3.Future<List<String>> getFavoriteMediaIds() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteMediaIds,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> getFavoriteDirectoryIds() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteDirectoryIds,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> addFavorite(String? mediaId) => (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [mediaId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addFavorites(List<_i4.FavoriteEntity>? favorites) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorites,
          [favorites],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeFavorite(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [itemId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeFavorites(List<String>? itemIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavorites,
          [itemIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isFavorite(
    String? itemId, {
    _i5.FavoriteItemType? type = _i5.FavoriteItemType.media,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [itemId],
          {#type: type},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
