// Mocks generated by Mockito 5.4.4 from annotations
// in media_fast_view/test/features/media_library/domain/use_cases/add_remove_clear_use_cases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:media_fast_view/core/utils/batch_update_result.dart' as _i2;
import 'package:media_fast_view/features/favorites/domain/entities/favorite_entity.dart'
    as _i10;
import 'package:media_fast_view/features/favorites/domain/entities/favorite_item_type.dart'
    as _i11;
import 'package:media_fast_view/features/favorites/domain/repositories/favorites_repository.dart'
    as _i9;
import 'package:media_fast_view/features/media_library/domain/entities/directory_entity.dart'
    as _i5;
import 'package:media_fast_view/features/media_library/domain/entities/directory_media_counts.dart'
    as _i8;
import 'package:media_fast_view/features/media_library/domain/entities/media_entity.dart'
    as _i7;
import 'package:media_fast_view/features/media_library/domain/repositories/directory_repository.dart'
    as _i3;
import 'package:media_fast_view/features/media_library/domain/repositories/media_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBatchUpdateResult_0 extends _i1.SmartFake
    implements _i2.BatchUpdateResult {
  _FakeBatchUpdateResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DirectoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDirectoryRepository extends _i1.Mock
    implements _i3.DirectoryRepository {
  MockDirectoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.DirectoryEntity>> getDirectories() => (super.noSuchMethod(
        Invocation.method(
          #getDirectories,
          [],
        ),
        returnValue: _i4.Future<List<_i5.DirectoryEntity>>.value(
            <_i5.DirectoryEntity>[]),
      ) as _i4.Future<List<_i5.DirectoryEntity>>);

  @override
  _i4.Future<_i5.DirectoryEntity?> getDirectoryById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDirectoryById,
          [id],
        ),
        returnValue: _i4.Future<_i5.DirectoryEntity?>.value(),
      ) as _i4.Future<_i5.DirectoryEntity?>);

  @override
  _i4.Future<void> addDirectory(
    _i5.DirectoryEntity? directory, {
    bool? silent = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDirectory,
          [directory],
          {#silent: silent},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeDirectory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #removeDirectory,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.DirectoryEntity>> searchDirectories(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDirectories,
          [query],
        ),
        returnValue: _i4.Future<List<_i5.DirectoryEntity>>.value(
            <_i5.DirectoryEntity>[]),
      ) as _i4.Future<List<_i5.DirectoryEntity>>);

  @override
  _i4.Future<List<_i5.DirectoryEntity>> filterDirectoriesByTags(
          List<String>? tagIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterDirectoriesByTags,
          [tagIds],
        ),
        returnValue: _i4.Future<List<_i5.DirectoryEntity>>.value(
            <_i5.DirectoryEntity>[]),
      ) as _i4.Future<List<_i5.DirectoryEntity>>);

  @override
  _i4.Future<void> updateDirectoryTags(
    String? directoryId,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDirectoryTags,
          [
            directoryId,
            tagIds,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.BatchUpdateResult> updateDirectoryTagsBatch(
          Map<String, List<String>>? directoryTags) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDirectoryTagsBatch,
          [directoryTags],
        ),
        returnValue:
            _i4.Future<_i2.BatchUpdateResult>.value(_FakeBatchUpdateResult_0(
          this,
          Invocation.method(
            #updateDirectoryTagsBatch,
            [directoryTags],
          ),
        )),
      ) as _i4.Future<_i2.BatchUpdateResult>);

  @override
  _i4.Future<void> updateDirectoryBookmark(
    String? directoryId,
    String? bookmarkData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDirectoryBookmark,
          [
            directoryId,
            bookmarkData,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateDirectoryMetadata(
    String? directoryId, {
    String? path,
    String? name,
    String? bookmarkData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDirectoryMetadata,
          [directoryId],
          {
            #path: path,
            #name: name,
            #bookmarkData: bookmarkData,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refreshChangedLibraryRoots() => (super.noSuchMethod(
        Invocation.method(
          #refreshChangedLibraryRoots,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllDirectories() => (super.noSuchMethod(
        Invocation.method(
          #clearAllDirectories,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [MediaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaRepository extends _i1.Mock implements _i6.MediaRepository {
  MockMediaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.MediaEntity>> getMediaForDirectoryPath(
    String? directoryPath, {
    String? bookmarkData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaForDirectoryPath,
          [directoryPath],
          {#bookmarkData: bookmarkData},
        ),
        returnValue:
            _i4.Future<List<_i7.MediaEntity>>.value(<_i7.MediaEntity>[]),
      ) as _i4.Future<List<_i7.MediaEntity>>);

  @override
  _i4.Future<List<_i7.MediaEntity>> getMediaForDirectory(String? directoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaForDirectory,
          [directoryId],
        ),
        returnValue:
            _i4.Future<List<_i7.MediaEntity>>.value(<_i7.MediaEntity>[]),
      ) as _i4.Future<List<_i7.MediaEntity>>);

  @override
  _i4.Future<List<_i7.MediaEntity>> getAllMedia() => (super.noSuchMethod(
        Invocation.method(
          #getAllMedia,
          [],
        ),
        returnValue:
            _i4.Future<List<_i7.MediaEntity>>.value(<_i7.MediaEntity>[]),
      ) as _i4.Future<List<_i7.MediaEntity>>);

  @override
  _i4.Future<Map<String, _i8.DirectoryMediaCounts>> getDirectoryMediaCounts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDirectoryMediaCounts,
          [],
        ),
        returnValue: _i4.Future<Map<String, _i8.DirectoryMediaCounts>>.value(
            <String, _i8.DirectoryMediaCounts>{}),
      ) as _i4.Future<Map<String, _i8.DirectoryMediaCounts>>);

  @override
  _i4.Future<_i7.MediaEntity?> getMediaById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getMediaById,
          [id],
        ),
        returnValue: _i4.Future<_i7.MediaEntity?>.value(),
      ) as _i4.Future<_i7.MediaEntity?>);

  @override
  _i4.Future<List<_i7.MediaEntity>> filterMediaByTagsForDirectory(
    List<String>? tagIds,
    String? directoryPath, {
    String? bookmarkData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterMediaByTagsForDirectory,
          [
            tagIds,
            directoryPath,
          ],
          {#bookmarkData: bookmarkData},
        ),
        returnValue:
            _i4.Future<List<_i7.MediaEntity>>.value(<_i7.MediaEntity>[]),
      ) as _i4.Future<List<_i7.MediaEntity>>);

  @override
  _i4.Future<List<_i7.MediaEntity>> filterMediaByTags(List<String>? tagIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterMediaByTags,
          [tagIds],
        ),
        returnValue:
            _i4.Future<List<_i7.MediaEntity>>.value(<_i7.MediaEntity>[]),
      ) as _i4.Future<List<_i7.MediaEntity>>);

  @override
  _i4.Future<void> updateMediaTags(
    String? mediaId,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMediaTags,
          [
            mediaId,
            tagIds,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.BatchUpdateResult> updateMediaTagsBatch(
          Map<String, List<String>>? mediaTags) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMediaTagsBatch,
          [mediaTags],
        ),
        returnValue:
            _i4.Future<_i2.BatchUpdateResult>.value(_FakeBatchUpdateResult_0(
          this,
          Invocation.method(
            #updateMediaTagsBatch,
            [mediaTags],
          ),
        )),
      ) as _i4.Future<_i2.BatchUpdateResult>);

  @override
  _i4.Future<void> removeMediaForDirectory(String? directoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMediaForDirectory,
          [directoryId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeMediaNotInDirectories(List<String>? directoryIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMediaNotInDirectories,
          [directoryIds],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllMedia() => (super.noSuchMethod(
        Invocation.method(
          #clearAllMedia,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> upsertMedia(List<_i7.MediaEntity>? media) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertMedia,
          [media],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [FavoritesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesRepository extends _i1.Mock
    implements _i9.FavoritesRepository {
  MockFavoritesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i10.FavoriteEntity>> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: _i4.Future<List<_i10.FavoriteEntity>>.value(
            <_i10.FavoriteEntity>[]),
      ) as _i4.Future<List<_i10.FavoriteEntity>>);

  @override
  _i4.Future<List<String>> getFavoriteMediaIds() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteMediaIds,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<String>> getFavoriteDirectoryIds() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteDirectoryIds,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> addFavorite(String? mediaId) => (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [mediaId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addFavorites(List<_i10.FavoriteEntity>? favorites) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorites,
          [favorites],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFavorite(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [itemId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFavorites(List<String>? itemIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavorites,
          [itemIds],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isFavorite(
    String? itemId, {
    _i11.FavoriteItemType? type = _i11.FavoriteItemType.media,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [itemId],
          {#type: type},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
