// Mocks generated by Mockito 5.4.4 from annotations
// in media_fast_view/test/features/media_library/domain/use_cases/get_media_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:media_fast_view/core/utils/batch_update_result.dart' as _i2;
import 'package:media_fast_view/features/media_library/domain/entities/directory_media_counts.dart'
    as _i6;
import 'package:media_fast_view/features/media_library/domain/entities/media_entity.dart'
    as _i5;
import 'package:media_fast_view/features/media_library/domain/repositories/media_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBatchUpdateResult_0 extends _i1.SmartFake
    implements _i2.BatchUpdateResult {
  _FakeBatchUpdateResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MediaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaRepository extends _i1.Mock implements _i3.MediaRepository {
  MockMediaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.MediaEntity>> getMediaForDirectoryPath(
    String? directoryPath, {
    String? bookmarkData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaForDirectoryPath,
          [directoryPath],
          {#bookmarkData: bookmarkData},
        ),
        returnValue:
            _i4.Future<List<_i5.MediaEntity>>.value(<_i5.MediaEntity>[]),
      ) as _i4.Future<List<_i5.MediaEntity>>);

  @override
  _i4.Future<List<_i5.MediaEntity>> getMediaForDirectory(String? directoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaForDirectory,
          [directoryId],
        ),
        returnValue:
            _i4.Future<List<_i5.MediaEntity>>.value(<_i5.MediaEntity>[]),
      ) as _i4.Future<List<_i5.MediaEntity>>);

  @override
  _i4.Future<List<_i5.MediaEntity>> getAllMedia() => (super.noSuchMethod(
        Invocation.method(
          #getAllMedia,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.MediaEntity>>.value(<_i5.MediaEntity>[]),
      ) as _i4.Future<List<_i5.MediaEntity>>);

  @override
  _i4.Future<Map<String, _i6.DirectoryMediaCounts>> getDirectoryMediaCounts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDirectoryMediaCounts,
          [],
        ),
        returnValue: _i4.Future<Map<String, _i6.DirectoryMediaCounts>>.value(
            <String, _i6.DirectoryMediaCounts>{}),
      ) as _i4.Future<Map<String, _i6.DirectoryMediaCounts>>);

  @override
  _i4.Future<_i5.MediaEntity?> getMediaById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getMediaById,
          [id],
        ),
        returnValue: _i4.Future<_i5.MediaEntity?>.value(),
      ) as _i4.Future<_i5.MediaEntity?>);

  @override
  _i4.Future<List<_i5.MediaEntity>> filterMediaByTagsForDirectory(
    List<String>? tagIds,
    String? directoryPath, {
    String? bookmarkData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterMediaByTagsForDirectory,
          [
            tagIds,
            directoryPath,
          ],
          {#bookmarkData: bookmarkData},
        ),
        returnValue:
            _i4.Future<List<_i5.MediaEntity>>.value(<_i5.MediaEntity>[]),
      ) as _i4.Future<List<_i5.MediaEntity>>);

  @override
  _i4.Future<List<_i5.MediaEntity>> filterMediaByTags(List<String>? tagIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterMediaByTags,
          [tagIds],
        ),
        returnValue:
            _i4.Future<List<_i5.MediaEntity>>.value(<_i5.MediaEntity>[]),
      ) as _i4.Future<List<_i5.MediaEntity>>);

  @override
  _i4.Future<void> updateMediaTags(
    String? mediaId,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMediaTags,
          [
            mediaId,
            tagIds,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.BatchUpdateResult> updateMediaTagsBatch(
          Map<String, List<String>>? mediaTags) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMediaTagsBatch,
          [mediaTags],
        ),
        returnValue:
            _i4.Future<_i2.BatchUpdateResult>.value(_FakeBatchUpdateResult_0(
          this,
          Invocation.method(
            #updateMediaTagsBatch,
            [mediaTags],
          ),
        )),
      ) as _i4.Future<_i2.BatchUpdateResult>);

  @override
  _i4.Future<void> removeMediaForDirectory(String? directoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMediaForDirectory,
          [directoryId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeMediaNotInDirectories(List<String>? directoryIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMediaNotInDirectories,
          [directoryIds],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllMedia() => (super.noSuchMethod(
        Invocation.method(
          #clearAllMedia,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> upsertMedia(List<_i5.MediaEntity>? media) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertMedia,
          [media],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
